/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Graph, GraphInterface } from "../Graph";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50601680601d6000396000f3fe6080604052600080fdfea164736f6c6343000809000a";

type GraphConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GraphConstructorParams,
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Graph__factory extends ContractFactory {
  constructor(...args: GraphConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "Graph";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<Graph> {
    return super.deploy(overrides || {}) as Promise<Graph>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Graph {
    return super.attach(address) as Graph;
  }
  connect(signer: Signer): Graph__factory {
    return super.connect(signer) as Graph__factory;
  }
  static readonly contractName: "Graph";
  public readonly contractName: "Graph";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GraphInterface {
    return new utils.Interface(_abi) as GraphInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Graph {
    return new Contract(address, _abi, signerOrProvider) as Graph;
  }
}
