/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  UnshieldedGraph,
  UnshieldedGraphInterface,
} from "../UnshieldedGraph";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50601680601d6000396000f3fe6080604052600080fdfea164736f6c6343000809000a";

type UnshieldedGraphConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UnshieldedGraphConstructorParams,
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class UnshieldedGraph__factory extends ContractFactory {
  constructor(...args: UnshieldedGraphConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "UnshieldedGraph";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<UnshieldedGraph> {
    return super.deploy(overrides || {}) as Promise<UnshieldedGraph>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): UnshieldedGraph {
    return super.attach(address) as UnshieldedGraph;
  }
  connect(signer: Signer): UnshieldedGraph__factory {
    return super.connect(signer) as UnshieldedGraph__factory;
  }
  static readonly contractName: "UnshieldedGraph";
  public readonly contractName: "UnshieldedGraph";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UnshieldedGraphInterface {
    return new utils.Interface(_abi) as UnshieldedGraphInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): UnshieldedGraph {
    return new Contract(address, _abi, signerOrProvider) as UnshieldedGraph;
  }
}
