/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Axiom",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Axiom__factory>;
    getContractFactory(
      name: "DiscountedBalance",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DiscountedBalance__factory>;
    getContractFactory(
      name: "IssuanceNode",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IssuanceNode__factory>;
    getContractFactory(
      name: "Graph",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Graph__factory>;
    getContractFactory(
      name: "IGraphNode",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGraphNode__factory>;
    getContractFactory(
      name: "UnshieldedGraph",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UnshieldedGraph__factory>;
    getContractFactory(
      name: "Greeter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Greeter__factory>;
    getContractFactory(
      name: "Patch",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Patch__factory>;

    getContractAt(
      name: "Axiom",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Axiom>;
    getContractAt(
      name: "DiscountedBalance",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DiscountedBalance>;
    getContractAt(
      name: "IssuanceNode",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IssuanceNode>;
    getContractAt(
      name: "Graph",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Graph>;
    getContractAt(
      name: "IGraphNode",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IGraphNode>;
    getContractAt(
      name: "UnshieldedGraph",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UnshieldedGraph>;
    getContractAt(
      name: "Greeter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Greeter>;
    getContractAt(
      name: "Patch",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Patch>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
